[build]
compiler = "g++"

[[targets]]
name = "main"
src = "./src/"
include_dir = "./src/include"
type = "exe"
cflags = "-g -std=c++17 -Wall -Wextra -Wpedantic"
libs = "-lglew32 -lglfw3 -lopengl32 -lm"